Pulls champion key ids from datadragon. Not much to see here

In [1]:
import pandas as pd
from riotwatcher import LolWatcher, ApiError

with open('data/api-key.txt', 'r') as api:
    API_KEY = api.read()
lol_watcher = LolWatcher(API_KEY)

REGION = "kr"

In [2]:
# check league's latest version
latest = lol_watcher.data_dragon.versions_for_region(REGION)['n']['champion']
# get some champions static information
static_champ_list = lol_watcher.data_dragon.champions(latest, False, 'en_US')

In [3]:
# get champion info and use champion key as index
champ_name_df=pd.DataFrame(static_champ_list["data"]).T[["id","key","name","stats"]]
champ_name_df[champ_name_df["name"]!=champ_name_df.index]
champ_name_df["key"]=champ_name_df["key"].astype(int)
champ_name_df=champ_name_df.reset_index()
champ_name_df=champ_name_df.set_index("key")
champ_name_df

,index,id,name,stats
key,,,,
266,Aatrox,Aatrox,Aatrox,"{'hp': 580, 'hpperlevel': 90, 'mp': 0, 'mpperl..."
103,Ahri,Ahri,Ahri,"{'hp': 526, 'hpperlevel': 92, 'mp': 418, 'mppe..."
84,Akali,Akali,Akali,"{'hp': 575, 'hpperlevel': 95, 'mp': 200, 'mppe..."
12,Alistar,Alistar,Alistar,"{'hp': 600, 'hpperlevel': 106, 'mp': 350, 'mpp..."
32,Amumu,Amumu,Amumu,"{'hp': 613.12, 'hpperlevel': 84, 'mp': 287.2, ..."
...,...,...,...,...
238,Zed,Zed,Zed,"{'hp': 584, 'hpperlevel': 85, 'mp': 200, 'mppe..."
115,Ziggs,Ziggs,Ziggs,"{'hp': 536, 'hpperlevel': 92, 'mp': 480, 'mppe..."
26,Zilean,Zilean,Zilean,"{'hp': 504, 'hpperlevel': 82, 'mp': 452, 'mppe..."
142,Zoe,Zoe,Zoe,"{'hp': 560, 'hpperlevel': 92, 'mp': 425, 'mppe..."
143,Zyra,Zyra,Zyra,"{'hp': 504, 'hpperlevel': 79, 'mp': 418, 'mppe..."

In [4]:
# returning the index to column after sorting it and then not saving the index...
# v silly could fix but its fine
key_name = champ_name_df["id"].sort_index().reset_index()

In [5]:
key_name.to_csv("data/champion-key-ids.csv", index=False)